// Component + pattern documentation. One source for components.md and the artifact's components/<Name>/README.md.
export const COMPONENTS = [
  {
    name: 'Button', group: 'Actions', kind: 'component',
    summary: 'Triggers an action; one primary per view, everything else secondary, ghost or link.',
    anatomy: 'Container (height 28/36/44px, radius-md; radius-sm at sm) · optional leading icon (16px) · label (text-sm 500; text-base at lg) · optional trailing icon · spinner when loading.',
    variants: 'primary (accent fill) · secondary (surface + border-strong outline) · ghost (transparent, text-muted) · destructive (error fill) · link (inline, accent-text, underlined). Sizes sm 28px / md 36px / lg 44px. Icon-only: square, same heights, `aria-label` required. Block: full width (mobile CTAs).',
    states: 'default · hover (accent-hover / surface-hover) · focus-visible (2px focus-ring, 2px offset) · active (accent-active / surface-sunken) · disabled (surface-hover fill + text-disabled, `cursor:not-allowed`) · loading (`aria-busy="true"`, spinner replaces leading icon, label changes to a present participle, width kept).',
    tokens: '`accent`, `accent-hover`, `accent-active`, `accent-fg`, `surface`, `surface-hover`, `surface-sunken`, `border-strong`, `text`, `text-muted`, `text-disabled`, `error`, `error-hover`, `error-fg`, `accent-text`, `focus-ring`, `radius-md`, `radius-sm`, `space-2..5`, `text-sm`, `text-base`, `duration-fast`, `ease-standard`.',
    a11y: 'Use `<button>` for actions and `<a>` for navigation. Icon-only buttons need `aria-label`. Loading keeps focus and sets `aria-busy`; announce completion via a toast (`role="status"`). Destructive actions that cannot be undone go through a Modal. Hit target ≥ 44px on touch (use lg or pad the row).',
    do: 'Write verbs: "Send reply", "Join waitlist". Keep one primary per region. Pair destructive with an undo toast where possible.',
    dont: 'Don\'t put two primaries side by side. Don\'t use link style for actions that change data. Don\'t shorten "Cancel" to an icon.',
  },
  {
    name: 'Input', group: 'Forms', kind: 'component',
    summary: 'Single-line text entry with label, hint and error message.',
    anatomy: 'Field wrapper (grid, gap space-1.5) · label (text-sm 500, text) · control (36px, or 44px `--lg`; radius-md; 1px border-strong; surface) · optional leading icon (text-subtle) and trailing kbd hint · hint (text-xs, text-subtle) or error (text-xs, error-text, icon).',
    variants: 'md 36px (app) · lg 44px (marketing forms) · with leading icon (search) · with trailing shortcut hint.',
    states: 'default · hover (border → text-subtle) · focus-visible (2px focus-ring inside, border focus-ring) · invalid (`aria-invalid="true"`, border error, message below) · disabled (surface-sunken, text-disabled, border) · read-only (as default, no hover).',
    tokens: '`surface`, `surface-sunken`, `border-strong`, `border`, `text`, `text-subtle`, `text-disabled`, `focus-ring`, `error`, `error-text`, `radius-md`, `space-3`, `space-4`, `text-sm`, `text-xs`.',
    a11y: 'Always a visible `<label>` (placeholder is not a label). Link hint/error with `aria-describedby`. Error text says how to fix it. Border-strong meets 3:1 on every surface; placeholder uses text-subtle (≥4.5:1).',
    do: 'Use `type="email"` and `autocomplete` values. Validate on blur, not on every keystroke.',
    dont: 'Don\'t rely on red alone; always include the message and icon. Don\'t disable the submit button to signal errors.',
  },
  {
    name: 'Select', group: 'Forms', kind: 'component',
    summary: 'Pick one option from a short list; native `<select>` styled to match Input.',
    anatomy: 'Same field shell as Input · native `<select>` (appearance none, 36px) · CSS chevron (text-muted) at right 14px.',
    variants: 'md 36px · lg 44px (use `zl-input--lg` metrics) · with hint · invalid.',
    states: 'default · hover · focus-visible · invalid · disabled — identical tokens to Input.',
    tokens: 'Input tokens plus `text-muted` for the chevron.',
    a11y: 'Keep the native element for keyboard and screen-reader support. For > 10 options or search, use a combobox pattern (not in v1).',
    do: 'Order options by likelihood; make the default the safest choice.',
    dont: 'Don\'t use a select for 2 options (use a Toggle or Tabs/segmented).',
  },
  {
    name: 'Checkbox', group: 'Forms', kind: 'component',
    summary: 'Independent on/off choices, including a mixed (indeterminate) parent.',
    anatomy: 'Visually hidden native input · 18px box (radius-xs, 1.5px border-strong) · check mark or dash (accent-fg on accent) · label (text-sm) · optional description (text-xs, text-subtle).',
    variants: 'unchecked · checked · indeterminate · with description.',
    states: 'default · hover (surface-hover fill) · focus-visible (ring on the box) · active (surface-sunken) · disabled (border, surface-sunken; label text-disabled) · disabled checked.',
    tokens: '`border-strong`, `surface`, `surface-hover`, `surface-sunken`, `accent`, `accent-fg`, `text`, `text-subtle`, `text-disabled`, `focus-ring`, `radius-xs`.',
    a11y: 'Native `<input type="checkbox">` inside a `<label>`; set `.indeterminate` in JS for mixed. Box border meets 3:1.',
    do: 'Use for settings that apply on save and for multi-select in lists.',
    dont: 'Don\'t use for instant on/off settings (use Toggle).',
  },
  {
    name: 'Toggle', group: 'Forms', kind: 'component',
    summary: 'Switch for a setting that takes effect immediately (e.g. auto-draft replies).',
    anatomy: 'Track 36×20 (radius-full) · knob 16px (neutral-0, shadow-xs) · adjacent label.',
    variants: 'off (track border-strong) · on (track accent).',
    states: 'default · hover (track text-subtle / accent-hover) · focus-visible (ring) · active (knob stretches to 19px) · disabled (surface-sunken track, border knob) · loading (`aria-busy`, knob pulses while saving).',
    tokens: '`border-strong`, `text-subtle`, `accent`, `accent-hover`, `surface-sunken`, `border`, `neutral-0`, `shadow-xs`, `focus-ring`, `duration-base`, `ease-standard`.',
    a11y: '`<button role="switch" aria-checked>` with a visible label or `aria-label`. Off track meets 3:1 against surfaces. Motion is transform only and collapses under reduced motion.',
    do: 'Apply immediately and confirm with a toast if the effect is not visible.',
    dont: 'Don\'t put toggles in forms that need a Save button.',
  },
  {
    name: 'Badge', group: 'Status', kind: 'component',
    summary: 'Short status or label chip; the AI variant marks anything the agent decided.',
    anatomy: 'Pill (22px, radius-full, 1px tinted border) · optional dot (6px) or 12px icon · label (text-xs 500).',
    variants: 'neutral · ai/accent (accent-subtle + accent-text + agent glyph) · success · warning · error · info · outline · solid (accent fill, for "Recommended"/"New").',
    states: 'Static. When clickable (filter chip), follow Button ghost states and add focus-visible ring.',
    tokens: '`surface-sunken`, `text-muted`, `accent-subtle`, `accent-text`, `accent-border`, `{status}-subtle`, `{status}-text`, `{status}-border`, `accent`, `accent-fg`, `radius-full`, `text-xs`.',
    a11y: 'Color is never the only signal: every status badge has a word, and AI badges carry the agent glyph. All text pairs ≥ 4.5:1 in both themes.',
    do: 'Keep to 1–2 words. Use the AI badge only for agent-generated labels ("Needs reply", "Draft ready").',
    dont: 'Don\'t stack more than two badges in an inbox row. Don\'t invent new hues for labels.',
  },
  {
    name: 'Card', group: 'Layout', kind: 'component',
    summary: 'Groups related content on a surface; can be static, interactive, selected or raised.',
    anatomy: 'Container (surface, 1px border, radius-lg, padding space-6) · optional icon tile (36px, accent-subtle) · title (text-lg 600) · body (text-sm, text-muted) · optional footer actions.',
    variants: 'default · interactive (whole card is a link) · selected (accent outline) · raised (surface-raised + shadow-md, no border) · sunken (bg-subtle).',
    states: 'interactive: hover (border-strong + shadow-sm) · focus-visible (ring) · active (surface-hover, no shadow). Disabled cards are not used; hide or explain instead.',
    tokens: '`surface`, `surface-raised`, `bg-subtle`, `border`, `border-strong`, `accent`, `accent-subtle`, `accent-text`, `text`, `text-muted`, `shadow-sm`, `shadow-md`, `radius-lg`, `space-6`.',
    a11y: 'Interactive cards are a single `<a>`/`<button>`; don\'t nest other interactive elements inside. Headings inside cards keep the page outline order.',
    do: 'Use cards for comparable items (features, plans, quotes).',
    dont: 'Don\'t nest cards. Don\'t add colored left borders.',
  },
  {
    name: 'NavBar', group: 'Navigation', kind: 'component',
    summary: 'Sticky top bar with the mark, primary links and the single primary CTA.',
    anatomy: 'Bar (64px, bg, bottom border, z-nav) · brand (mark 28px + wordmark text-lg 600) · link list (36px items, text-sm 500) · actions (ghost "Sign in" + primary CTA) · menu button (below md).',
    variants: 'default (≥ 768px) · compact (< 768px: links and ghost action collapse into a menu button that opens a sheet).',
    states: 'link: default (text-muted) · hover (text + surface-hover) · focus-visible (ring) · current (`aria-current="page"`, text + 2px accent underline).',
    tokens: '`bg`, `border`, `text`, `text-muted`, `surface-hover`, `accent`, `focus-ring`, `z-nav`, `space-4..8`, `radius-md`.',
    a11y: '`<nav aria-label="Main">`. Menu button uses `aria-expanded` and `aria-controls`. Provide a "Skip to content" link as the first focusable element.',
    do: 'Keep ≤ 5 links. Keep the CTA label identical to the hero CTA.',
    dont: 'Don\'t add a second filled button. Don\'t hide the CTA on mobile.',
  },
  {
    name: 'Footer', group: 'Navigation', kind: 'component',
    summary: 'Closing site navigation, brand line and legal row on bg-subtle.',
    anatomy: 'Band (bg-subtle, top border, padding space-12/6/8) · brand column (mark + one sentence) · 3 link columns (uppercase text-xs heading in text-subtle, text-sm links) · bottom row (divider, text-xs legal + status).',
    variants: 'desktop 4 columns · mobile: brand full width, links 2 columns.',
    states: 'links: default (text-muted) · hover (text + underline) · focus-visible (ring).',
    tokens: '`bg-subtle`, `border`, `text`, `text-muted`, `text-subtle`, `focus-ring`, `space-2..12`, `text-xs`, `text-sm`.',
    a11y: '`<footer>` with each column as `<nav aria-label>`. Links are real text, not icons alone.',
    do: 'Keep the legal line short. Link Security and Privacy.',
    dont: 'Don\'t repeat the full nav plus a newsletter form plus social icons; pick what matters.',
  },
  {
    name: 'Modal', group: 'Overlays', kind: 'component',
    summary: 'Blocking dialog for a confirmation or a short focused task.',
    anatomy: 'Scrim (overlay, z-overlay) · dialog (max-width 480, surface-raised, radius-xl, shadow-xl, 1px border) · header (title text-xl 600 + close icon button) · body (text-sm, text-muted) · footer (bg-subtle, right-aligned secondary + primary).',
    variants: 'confirm (2 actions) · destructive (primary is destructive) · form (inputs in body).',
    states: 'enter: fade + 8px rise, duration-slow, ease-enter · exit: fade, duration-fast, ease-exit · reduced motion: fade only.',
    tokens: '`overlay`, `surface-raised`, `border`, `bg-subtle`, `text`, `text-muted`, `shadow-xl`, `radius-xl`, `z-overlay`, `z-modal`, `duration-slow`, `ease-enter`.',
    a11y: 'Use `<dialog>` or `role="dialog" aria-modal="true"` with `aria-labelledby`/`aria-describedby`. Trap focus, focus the primary (or first field) on open, return focus on close, Esc closes.',
    do: 'Title as a question for confirmations; buttons repeat the verb ("Send reply").',
    dont: 'Don\'t use a modal for information that could be a toast. Don\'t stack modals.',
  },
  {
    name: 'Toast', group: 'Overlays', kind: 'component',
    summary: 'Brief, non-blocking confirmation of what the user or the agent just did, often with Undo.',
    anatomy: 'Container (max 380px, surface-raised, border, radius-lg, shadow-lg) · status icon or spinner · title (600) + description (text-muted) · actions (link "Undo", secondary "Retry", dismiss icon).',
    variants: 'success · info · warning · error · agent/loading (spinner, "Drafting a reply…").',
    states: 'enter: 8px rise + fade (duration-slow, ease-enter) · auto-dismiss after 6s (never for error) · pause on hover/focus · reduced motion: fade only.',
    tokens: '`surface-raised`, `border`, `shadow-lg`, `text`, `text-muted`, `success`, `warning`, `error`, `info`, `accent`, `radius-lg`, `z-toast`.',
    a11y: '`role="status"` (polite) for success/info/loading; `role="alert"` for errors. Actions reachable by keyboard (F6 or a shortcut to focus the stack). Icons have text equivalents.',
    do: 'Say what happened in past tense ("Archived 18 threads"). Offer Undo for agent actions.',
    dont: 'Don\'t use toasts for errors that block a task; show them inline.',
  },
  {
    name: 'Tabs', group: 'Navigation', kind: 'component',
    summary: 'Switch between views of the same context (inbox views, billing period).',
    anatomy: 'Tablist (bottom border) · tab (40px, text-sm 500) · optional count (mono text-xs) · selected indicator (2px accent bar).',
    variants: 'underline (default) · segmented (surface-sunken track, selected pill surface-raised + shadow-sm).',
    states: 'default (text-muted) · hover (text) · focus-visible (ring) · selected (text + accent bar; count accent-text) · disabled (text-disabled).',
    tokens: '`border`, `text`, `text-muted`, `text-subtle`, `text-disabled`, `accent`, `accent-text`, `surface-sunken`, `surface-raised`, `shadow-sm`, `focus-ring`.',
    a11y: 'WAI-ARIA tabs: `role="tablist"`, `role="tab"` + `aria-selected`, roving tabindex, arrow keys move, Home/End jump. Panels use `role="tabpanel"` + `aria-labelledby`.',
    do: 'Keep labels to 1–2 words; show counts only when they help decide.',
    dont: 'Don\'t use tabs for sequential steps.',
  },
  {
    name: 'InboxRow', group: 'Data display', kind: 'component',
    summary: 'One thread in a list: sender, subject, agent label and time, with actions on hover.',
    anatomy: 'Row (44px, radius-sm) · unread dot (8px) · sender (≤168px, ellipsis) + count · subject + optional snippet (text-subtle) · meta (≤2 badges) · time (text-xs, text-subtle, tabular) · hover actions (archive, snooze) replacing time. Group header: text-xs 500 text-subtle with hairline.',
    variants: 'unread (text + 600 weight + accent dot) · read (text-muted, 400) · selected (surface-selected + accent-border inset) · AI-labeled (AI badge in meta) · handled by agent (text-subtle, strikethrough subject). Mobile (< 768px): two lines, sender + time, then subject + badges.',
    states: 'hover (surface-hover, actions shown) · focus-visible (2px inset focus-ring, actions shown) · active/pressed (surface-sunken) · selected · loading (skeleton bars in surface-sunken).',
    tokens: '`surface`, `surface-hover`, `surface-selected`, `surface-sunken`, `accent`, `accent-border`, `text`, `text-muted`, `text-subtle`, `border`, `border-strong`, `focus-ring`, `radius-sm`, `text-sm`, `text-xs`.',
    a11y: 'List is `role="listbox"` (or a grid) with rows as options (`aria-selected`); unread state also in text for screen readers ("Unread, from Priya Raman…"). Weight + dot, not color alone, signal unread. Keyboard: j/k move, e archive, Enter open.',
    do: 'Keep one line on desktop, no avatars, max two badges.',
    dont: 'Don\'t show preview text on every row; reserve snippets for AI summaries.',
  },
  {
    name: 'EmptyState', group: 'Feedback', kind: 'component',
    summary: 'Calm "nothing to do" or "no results" message with a next step.',
    anatomy: 'Centered stack (max 420px) · 56px brand glyph on accent-subtle disc · title (text-xl 600) · body (text-sm, text-muted) · 1–2 actions (secondary + ghost).',
    variants: 'inbox clear (celebrate quietly, show what the agent handled) · no search results (suggest a broader query) · first run (connect account).',
    states: 'Static.',
    tokens: '`accent`, `accent-subtle`, `text`, `text-muted`, `space-2..12`, `text-xl`, `text-sm`.',
    a11y: 'The glyph is decorative (`aria-hidden`). Title is a heading at the right level.',
    do: 'Report what the agent did ("archived 61, drafted 12").',
    dont: 'Don\'t use confetti, mascots or guilt ("Inbox zero!").',
  },
  // ---------------- Patterns ----------------
  {
    name: 'Hero', group: 'Patterns', kind: 'pattern',
    summary: 'Opening section: one headline, one sentence, two CTAs, then a cropped product visual.',
    anatomy: 'Eyebrow badge (accent) · headline (display 76/76, 600, -0.04em; one accent-text word) · lead (text-xl, text-muted, max 34em) · CTA row (primary lg + secondary lg) · note (text-xs, text-subtle) · product frame cropped at the bottom (420px tall).',
    variants: 'centered (default) · split (text left, frame right) for secondary pages.',
    states: 'Responsive: < 768px headline drops to 5xl (48/52), CTAs stack full width, visual 320px tall; ≥ 1280px container 1152px.',
    tokens: '`bg`, `text`, `text-muted`, `text-subtle`, `accent-text`, `accent-subtle`, `text-display`, `text-5xl`, `text-xl`, `space-24`, `space-16`.',
    a11y: 'Single `<h1>`. The product frame has a text alternative (`role="img"` + `aria-label`) or is decorative when described in copy.',
    do: 'One idea: speed + calm. Keep the headline ≤ 8 words.',
    dont: 'Don\'t add avatars, logo walls or characters around the hero. No gradients behind the headline.',
  },
  {
    name: 'FeatureGrid', group: 'Patterns', kind: 'pattern',
    summary: 'Section head plus 3–6 feature cards in an auto-fit grid.',
    anatomy: 'Section (bg, space-24 vertical) · head (eyebrow, h2 text-4xl, lead) · grid (auto-fit, min 280px, gap space-4) · Card with icon tile, title, body.',
    variants: '3-up · 6-up (2 rows) · alternating (one large product visual per feature) for deeper pages.',
    states: 'Responsive: 3 → 2 → 1 columns via auto-fit.',
    tokens: 'Card tokens plus `accent-text` (eyebrow), `text-4xl`, `text-lg`.',
    a11y: 'Feature titles are `<h3>` under the section `<h2>`. Icons decorative.',
    do: 'Describe outcomes in plain words.',
    dont: 'Don\'t use emoji or illustrated characters as feature icons.',
  },
  {
    name: 'ScreenshotFrame', group: 'Patterns', kind: 'pattern',
    summary: 'Original, code-built product mockup (sidebar views, inbox rows, agent panel) used as the product visual.',
    anatomy: 'Frame (surface, border, radius-xl, shadow-xl) · title bar (40px, bg-subtle, mark + title + ⌘K hint) · sidebar (208px views with counts) · list (InboxRows) · agent activity panel (256px: activity items + a draft card).',
    variants: 'full (3 columns) · list-only (< 1024px) · cropped (inside Hero with fixed height and overflow hidden).',
    states: 'Static; may auto-play a subtle row highlight only when motion is allowed.',
    tokens: '`surface`, `bg-subtle`, `border`, `surface-selected`, `accent`, `accent-subtle`, `accent-border`, `accent-text`, `text-subtle`, `shadow-xl`, `radius-xl`, `font-mono`.',
    a11y: 'Treat as an image: `role="img"` with a descriptive `aria-label`; inner controls are not focusable (add `inert` in production).',
    do: 'Use realistic but fictional names and subjects.',
    dont: 'Never use Notion (or any third-party) screenshots; never show real customer data.',
  },
  {
    name: 'Testimonial', group: 'Patterns', kind: 'pattern',
    summary: 'Quote cards with clearly marked placeholder attribution until real, approved quotes exist.',
    anatomy: 'Section (bg-subtle) · centered head · grid of Cards (auto-fit 300px) · blockquote (text-lg; featured text-2xl) · figcaption (dashed initials avatar, name, "Placeholder" warning badge, role).',
    variants: 'grid of 3 · single featured quote.',
    states: 'Static.',
    tokens: '`bg-subtle`, `surface`, `border`, `border-strong`, `text`, `text-subtle`, `warning-subtle`, `warning-text`, `text-lg`, `text-2xl`.',
    a11y: '`<figure>` + `<blockquote>` + `<figcaption>`. Don\'t fake photos; initials avatar is `aria-hidden`.',
    do: 'Keep the "Placeholder" badge until legal approves a real quote.',
    dont: 'Don\'t invent names, companies, logos or stats and present them as real.',
  },
  {
    name: 'Pricing', group: 'Patterns', kind: 'pattern',
    summary: 'Three plan cards with a billing toggle; one plan featured.',
    anatomy: 'Head (h2, lead, segmented Monthly/Yearly) · grid (auto-fit 260px) · plan Card: name (+ solid badge), price (text-5xl) + period, description, feature list with check icons (accent-text), block CTA.',
    variants: 'default plan (secondary CTA) · featured (accent outline + shadow-lg, primary CTA, "Recommended" badge).',
    states: 'Billing toggle swaps prices; CTA states as Button.',
    tokens: 'Card tokens plus `accent`, `accent-text`, `accent-fg`, `shadow-lg`, `text-5xl`.',
    a11y: 'Price read as "$12 per user per month" (keep period in text). The featured plan is marked in text, not just by color.',
    do: 'Label placeholder prices as placeholders until validated.',
    dont: 'Don\'t use strikethrough "discount" prices or countdowns.',
  },
  {
    name: 'FAQ', group: 'Patterns', kind: 'pattern',
    summary: 'Accordion of short questions and answers.',
    anatomy: 'Centered column (max 760px) · `<details>` items separated by hairlines · summary (text-lg 500, chevron) · answer (text-base, text-muted, max 62ch).',
    variants: 'single-open or multi-open; first item open by default.',
    states: 'summary: default · hover (accent-text) · focus-visible (ring) · open (chevron rotates, duration-base).',
    tokens: '`border`, `text`, `text-muted`, `accent-text`, `focus-ring`, `duration-base`, `ease-standard`.',
    a11y: 'Native `<details>/<summary>` gives keyboard and SR support. Keep answers ≤ 3 sentences.',
    do: 'Answer the trust questions first (sending on your behalf, privacy).',
    dont: 'Don\'t hide pricing or data-use terms only inside the FAQ.',
  },
  {
    name: 'CTABand', group: 'Patterns', kind: 'pattern',
    summary: 'Closing call to action on the emphasis surface with an email field.',
    anatomy: 'Container (surface-emphasis, radius-2xl, padding space-16/10) · headline (text-4xl 600, text-on-emphasis) · one sentence · form (lg email input + primary lg button + note).',
    variants: 'with email form (waitlist) · button only.',
    states: 'Form states as Input and Button; success replaces the form with a success line (role="status").',
    tokens: '`surface-emphasis`, `text-on-emphasis`, `focus-ring-emphasis`, `surface`, `accent`, `accent-fg`, `radius-2xl`, `text-4xl`.',
    a11y: 'Input has a (visually hidden) label. Buttons in the band use focus-ring-emphasis, which passes 3:1 (`focus-ring-emphasis` vs `surface-emphasis` is in the contrast table).',
    do: 'Repeat the hero CTA label exactly.',
    dont: 'Don\'t add a second competing action.',
  },
];
