// Component + pattern documentation (v2). One source for components.md and the artifact's components/<Name>/README.md.
// Sizes and behaviour come from the reference app frames (see ../frame-audit.md); copy and data are ZeroLatency's own.
export const COMPONENTS = [
  // ---------------- Actions ----------------
  {
    name: 'Button', group: 'Actions', kind: 'component',
    summary: 'Triggers an action; one blue primary per region, everything else secondary, ghost, text or icon.',
    anatomy: 'Container (28px, radius-md; sm 24 · lg 32 · xl 40 for marketing) · optional 16px leading icon · label (text-md 500; 400 for secondary/ghost/text) · Split variant adds a 24px chevron segment divided by a 1px `accent-active` seam.',
    variants: 'primary (`accent` fill: Send, Save, Continue) · secondary (`surface-raised` + `shadow-sm` ring: Auto label, Open, Add property) · ghost (text-muted, fill on hover) · text (text-subtle, no fill until hover: Reset, Cc/Bcc) · danger (danger-text: Delete view) · icon (square, text-subtle; `aria-pressed="true"` turns it `accent`, as the active Filter tool) · split (Send ▾, Save ▾).',
    states: 'default · hover (`accent-hover` / `surface-hover`) · pressed (`accent-active` / `surface-selected`) · focus-visible (2px `focus-ring`, 2px offset) · busy (`aria-busy`, spinner + present participle: "Sending") · disabled (`text-disabled`, primary keeps a `surface-hover` fill).',
    tokens: '`accent`, `accent-hover`, `accent-active`, `accent-fg`, `surface-raised`, `surface-hover`, `surface-selected`, `text`, `text-muted`, `text-subtle`, `text-disabled`, `danger-text`, `danger-subtle`, `focus-ring`, `shadow-sm`, `radius-md`, `size-control-height*`, `text-md`, `duration-fast`.',
    a11y: '`<button>` for actions, `<a>` for navigation. Icon-only buttons need `aria-label` and should show a Tooltip with the shortcut. Toggle tools use `aria-pressed`. The split chevron is its own button with its own label ("Schedule send").',
    do: 'Use sentence-case verbs: "Send", "Save", "Auto label", "Delete view". Keep one primary per panel or menu footer.',
    dont: 'Don\'t put two primaries side by side. Don\'t use blue for anything that isn\'t the main action or an "on" state. Don\'t add borders; the secondary edge is the shadow ring.',
  },
  // ---------------- Forms ----------------
  {
    name: 'Input', group: 'Forms', kind: 'component',
    summary: 'Filled, borderless text field that gains a blue edge and halo on focus.',
    anatomy: 'Optional label (text-sm 500, text-muted) · control (28px, 34px for `--lg` names; radius-md; `surface-input` fill; 1px transparent border) · optional leading 16px icon (search) · hint (text-xs, text-subtle) or error (text-xs, danger-text).',
    variants: 'md 28px (menu search: "Filter by…", "Search grouping options…") · lg 34px (view and property names) · with leading icon · textarea.',
    states: 'default · hover (`border` edge) · focus (1px `focus-ring` border + 3px `focus-halo`, fill turns `bg`) · invalid (`aria-invalid`, `danger` edge + message) · disabled (`text-disabled`).',
    tokens: '`surface-input`, `bg`, `border`, `focus-ring`, `focus-halo`, `text`, `text-placeholder`, `text-subtle`, `danger`, `danger-text`, `radius-md`, `size-control-height`, `text-md`.',
    a11y: 'Every field needs a label: visible, or `aria-label` for menu search boxes whose purpose the placeholder states. Placeholders use `text-placeholder` (below 4.5:1 by design), so never put required information only in the placeholder. Link errors with `aria-describedby`.',
    do: 'Autofocus the search field when a menu opens. Filter as the user types.',
    dont: 'Don\'t add a resting border; the fill is the affordance. Don\'t use red alone for errors.',
  },
  {
    name: 'Select', group: 'Forms', kind: 'component',
    summary: 'Pick one value: an inline ghost trigger that opens a Menu with a check on the current value.',
    anatomy: 'Trigger (28px, text-muted value + 12px chevron, no fill until hover) · Menu listbox (`zl-menu`, items 28px, check on the selected item) · native `<select>` alternative styled like Input.',
    variants: 'inline trigger (settings rows: Theme mode, Thread style, Auto-advance, Font size) · native select (forms).',
    states: 'closed · hover (`surface-hover`) · open (`aria-expanded="true"`, keeps hover fill) · focus-visible · option hover/selected (`surface-hover`, trailing check).',
    tokens: '`text-muted`, `text-subtle`, `surface-hover`, `surface-raised`, `shadow-md`, `radius-md`, `radius-xl`.',
    a11y: 'Trigger: `aria-haspopup="listbox"` + `aria-expanded`. Options: `role="option"` + `aria-selected`. Arrow keys move, Enter picks, Esc closes and returns focus.',
    do: 'Right-align the trigger in a settings row, value first then chevron.',
    dont: 'Don\'t use it for more than ~8 options without a search field (use Menu with search).',
  },
  {
    name: 'Checkbox', group: 'Forms', kind: 'component',
    summary: '14px box for bulk selection and boolean properties.',
    anatomy: 'Hidden native input · 14px box (radius-xs, 1px `border-strong`) · white check on `accent` when checked · optional label.',
    variants: 'unchecked · checked · mixed (select-all with some rows chosen) · in-row (hidden until the row is hovered, focused or checked).',
    states: 'default · hover · focus-visible · checked · mixed · disabled.',
    tokens: '`border-strong`, `accent`, `accent-fg`, `bg`, `surface-hover`, `text-disabled`, `radius-xs`, `size-checkbox-size`.',
    a11y: 'Keep the native input for keyboard and screen readers; in-row checkboxes stay in the tab order even while visually hidden (they reveal on focus). The header box uses the mixed state (`indeterminate`).',
    do: 'Put the select-all box in the view header, aligned with the row boxes.',
    dont: 'Don\'t use a checkbox to trigger an immediate action (use a Toggle or Button).',
  },
  {
    name: 'Toggle', group: 'Forms', kind: 'component',
    summary: 'Switch for settings that apply immediately.',
    anatomy: 'Track 30×18 (`border-strong` off, `accent` on) · 14px white knob with `shadow-xs` · sits at the right of a settings row (title 14/500 + description 12 text-subtle).',
    variants: 'off · on · disabled.',
    states: 'default · hover · focus-visible · on · disabled.',
    tokens: '`border-strong`, `accent`, `gray-0`, `shadow-xs`, `surface-selected`, `radius-full`, `duration-base`.',
    a11y: '`role="switch"` + `aria-checked`, labelled by the row title. Space toggles.',
    do: 'Save instantly; no Save button in a settings pane.',
    dont: 'Don\'t use for choices with more than two values (use Select).',
  },
  // ---------------- Data display ----------------
  {
    name: 'Tag', group: 'Data display', kind: 'component',
    summary: 'Label chip: pastel fill with dark ink of the same hue, in nine inks.',
    anatomy: '20px chip · radius-sm (4px) · padding 0 6px · text-xs 500 · truncates at 132px with an ellipsis · overflow count "+N" in text-subtle.',
    variants: 'gray (default) · brown · orange · yellow · green · blue · purple · pink · red · accent (AI suggestion, "Included").',
    states: 'static. Editable tags open a Menu (see PropertyEditor).',
    tokens: '`tag-{ink}-bg`, `tag-{ink}-fg`, `accent-subtle`, `accent-text`, `text-subtle`, `radius-sm`, `size-chip-height`, `text-xs`.',
    a11y: 'Every fg/bg pair passes 4.5:1 in both themes. Colour is never the only signal: the chip always carries its word.',
    do: 'Let people pick the ink per label; default new labels to gray. Show at most two chips per row, then "+N".',
    dont: 'Don\'t use solid saturated fills. Don\'t put icons inside label chips.',
  },
  {
    name: 'Status', group: 'Data display', kind: 'component',
    summary: 'Status property pill: a 14px state glyph plus its word.',
    anatomy: '20px pill (radius-full) · glyph (dashed ring, play, check or cross in a filled circle) · label (text-md).',
    variants: 'Not started (no fill, dashed `icon-gray` ring; the default) · In progress (blue) · Done (green) · Canceled (red).',
    states: 'static in rows; opens the PropertyEditor menu when clicked.',
    tokens: '`tag-blue-*`, `tag-green-*`, `tag-red-*`, `icon-gray`, `icon-blue`, `icon-green`, `icon-red`, `radius-full`.',
    a11y: 'The word carries the state; the glyph is `aria-hidden`. Glyph shapes differ, so the set still reads in greyscale.',
    do: 'Keep the four default options; let people rename them in Edit property.',
    dont: 'Don\'t show the glyph without the word.',
  },
  {
    name: 'ThreadRow', group: 'Data display', kind: 'component',
    summary: 'One conversation in a view: sender, subject, label chips and time on a single 38px line.',
    anatomy: 'Grid: 20px checkbox · 8px unread dot (6px `accent`) · sender (≤200px, + thread count in `text-placeholder`) · subject (can start with an emoji) · meta (label chips, paperclip) · time (text-sm, text-subtle, tabular). Hover replaces the time with hover actions: Archive, Trash, Read/unread, Remind, Label.',
    variants: 'unread (dot + 600 weight on sender and subject) · read (400) · compact (32px) · simple (no sender column, used when grouped by sender) · with snippet ("· preview text" in text-subtle).',
    states: 'default · hover (`surface-hover`, checkbox + actions appear) · selected/open (`surface-selected`) · checked · focus-visible (inset ring).',
    tokens: '`surface-hover`, `surface-selected`, `accent`, `text`, `text-subtle`, `text-placeholder`, `radius-md`, `size-row-height`, `size-unread-dot`, `text-md`, `text-sm`.',
    a11y: 'List is `role="listbox"`, rows `role="option"` with `aria-selected`. Unread is announced through weight AND an sr-only "Unread" in production. Hover actions are also reachable by keyboard (e archive, # trash, u read, h remind, l label) and appear on focus.',
    do: 'Truncate sender and subject with an ellipsis; keep time right-aligned.',
    dont: 'Don\'t add avatars or preview lines by default; the row stays one line.',
  },
  {
    name: 'GroupHeading', group: 'Data display', kind: 'component',
    summary: 'Section header inside a view: a date bucket or a sender/domain group.',
    anatomy: '40px row · text-md 500 · aligned with the sender column (44px inset) · 1px `border` rule below · optional monogram for sender groups · hover actions "Collapse" and "Remove" (text buttons).',
    variants: 'date (Today, Yesterday, Last 7 days, March…) · keyword/sender (monogram + address) · property (status, label).',
    states: 'default · hover (actions fade in) · collapsed.',
    tokens: '`text`, `text-subtle`, `border`, `size-avatar-size`, `duration-fast`.',
    a11y: 'Use `role="presentation"` inside the listbox, or group rows with `role="group"` + `aria-label`. Collapse is a real button with `aria-expanded`.',
    do: 'Leave a space-2 gap above each heading so groups breathe.',
    dont: 'Don\'t use boxes or cards for groups; a hairline is enough.',
  },
  {
    name: 'EmptyState', group: 'Data display', kind: 'component',
    summary: 'Centred, quiet message for an empty view or a filter with no results.',
    anatomy: 'Optional 20px icon (`text-placeholder`) · optional title (text-md 500) · one line (text-sm, text-subtle).',
    variants: 'no results ("No filter results") · empty view (title + one line).',
    states: 'static.',
    tokens: '`text`, `text-subtle`, `text-placeholder`, `space-12`.',
    a11y: 'Announce with `role="status"` when it replaces results after filtering.',
    do: 'Say what will appear here and when.',
    dont: 'No illustrations, confetti or inbox-zero celebration.',
  },
  // ---------------- Navigation ----------------
  {
    name: 'Sidebar', group: 'Navigation', kind: 'component',
    summary: 'Left navigation: account, search, the user\'s views, mail folders and footer tools.',
    anatomy: '240px column on `bg-sidebar`, padding 8px · account row (20px avatar, name 14/500, email 12 subtle, switch chevron, compose icon) · Search item · "Views" section label with + (new view) · view items (30px, radius-md, 18px coloured filled glyph, label, count) · nested items for grouped views (26px inset, monogram) · "Less/More" toggle · "Mail" section (line icons: All mail, Sent, Drafts, Spam, Trash) · footer icon row (settings, calendar, help).',
    variants: 'expanded · collapsed (hidden; the viewbar shows an expand button) · with nested group items.',
    states: 'item: default · hover (`surface-hover`) · current (`surface-selected`, 500 weight) · focus-visible (inset ring) · dragging (reorder).',
    tokens: '`bg-sidebar`, `surface-hover`, `surface-selected`, `text`, `text-muted`, `text-subtle`, `icon-*`, `radius-md`, `size-sidebar-width`, `size-nav-item-height`, `text-md`, `text-xs`.',
    a11y: '`<nav aria-label="Mailbox">`; the current view has `aria-current="page"`. Counts are unread counts: expose them in the accessible name ("Inbox, 4 unread"). View icons are decorative.',
    do: 'Give each view one ink and one glyph; let people reorder by drag.',
    dont: 'Don\'t colour the selected item blue; selection is a gray fill.',
  },
  {
    name: 'ViewHeader', group: 'Navigation', kind: 'component',
    summary: 'The 44px toolbar above a view: select-all, view name and the view tools.',
    anatomy: 'Select-all checkbox · view glyph + name (text-md 500) · right cluster: "Auto label" secondary button, Filter (turns `accent` when filters apply), Group by, Edit view (gear), Refresh — all 28px icon buttons with tooltips.',
    variants: 'default · filtered (Filter icon `aria-pressed`) · with sidebar collapsed (leading expand button).',
    states: 'tools: default · hover · pressed/open · focus-visible.',
    tokens: '`bg`, `text`, `text-subtle`, `accent`, `surface-raised`, `shadow-sm`, `size-header-height`.',
    a11y: 'Each icon tool has an `aria-label` and a Tooltip that shows its shortcut (Filter: Ctrl F, Edit view: Ctrl E).',
    do: 'Open Filter and Group by as anchored Menus; open Edit view as a SidePanel.',
    dont: 'Don\'t add a page title above it; the view name is the title.',
  },
  {
    name: 'Tabs', group: 'Navigation', kind: 'component',
    summary: 'Small underline tabs for switching panes inside a popover (Emojis / Icons / Upload).',
    anatomy: 'Tab list with a 1px `border` baseline · tab (text-sm, text-subtle) · selected tab (text, 500, 2px underline in `text`).',
    variants: 'popover tabs (default).',
    states: 'default · hover (text) · selected · focus-visible.',
    tokens: '`text`, `text-subtle`, `border`, `text-sm`.',
    a11y: '`role="tablist"`, tabs `role="tab"` with `aria-selected`; arrow keys move between tabs.',
    do: 'Keep labels to one word.',
    dont: 'Don\'t use blue for the selected tab; ink only.',
  },
  // ---------------- Overlays ----------------
  {
    name: 'Menu', group: 'Overlays', kind: 'component',
    summary: 'Floating list anchored to a trigger: filters, group-by options, new-view choices, property options.',
    anatomy: '300px (340 wide) · `surface-raised`, radius-xl, `shadow-md`, padding 6px · optional title row · optional search Input at the top · section labels (text-xs 500 subtle: "Applied", "Suggested views") · items (28px, radius-md, 16px icon + label + trailing hint/chevron/check) · two-line items (44px: label + text-xs description) · 1px separators bleeding to the edges · optional footer (Reset + split Save).',
    variants: 'filter menu (applied filters with value hints, then available fields; "(Gmail)" marks provider categories in `text-placeholder`) · group-by menu (two-line items, check on the current grouping) · action menu (New view) · listbox (Select).',
    states: 'item: default · hover/active-descendant (`surface-hover`) · selected (check) · disabled · focus-visible.',
    tokens: '`surface-raised`, `shadow-md`, `surface-hover`, `border`, `text`, `text-muted`, `text-subtle`, `text-placeholder`, `radius-xl`, `radius-md`, `size-popover-width`, `size-menu-item-height`, `size-menu-item-2line-height`.',
    a11y: 'Menus of actions: `role="menu"`/`menuitem`; pickers: `role="listbox"`/`option`; with a search field use the combobox pattern (`aria-activedescendant`). Esc closes and returns focus to the trigger.',
    do: 'Autofocus search; filter live; keep the hint short ("is not", "contains …").',
    dont: 'Don\'t nest more than one level; a sub-step replaces the menu content with a back arrow (see FilterEditor).',
  },
  {
    name: 'FilterEditor', group: 'Overlays', kind: 'component',
    summary: 'The second step of a filter menu: edit one condition, confirm with Save.',
    anatomy: 'Menu shell · title row (back arrow, field name, operator dropdown "contains ▾", delete icon) · Input ("Add new entry") · matching entries with monogram and check · footer: Reset (text) and split Save (primary).',
    variants: 'text condition (contains / does not contain) · pick-from-list (mailboxes with checkboxes) · date range.',
    states: 'empty · typing (suggestions) · entries checked · saving.',
    tokens: 'Menu tokens + `accent`, `accent-fg`, `text-subtle`.',
    a11y: 'Back returns to the field list without losing edits. Save applies and closes; Esc discards.',
    do: 'Show the applied value as a hint on the parent menu row.',
    dont: 'Don\'t apply until Save.',
  },
  {
    name: 'Tooltip', group: 'Overlays', kind: 'component',
    summary: 'Dark label for icon buttons, with an optional shortcut line.',
    anatomy: '`surface-tooltip` fill, radius-md, padding 5×8 · title (text-xs 500, `text-on-tooltip`) · shortcut (text-2xs, `text-on-tooltip-muted`).',
    variants: 'label only · label + shortcut.',
    states: 'appears after 500ms hover or on focus; hides on Esc/blur.',
    tokens: '`surface-tooltip`, `text-on-tooltip`, `text-on-tooltip-muted`, `radius-md`, `shadow-md`, `text-xs`, `text-2xs`.',
    a11y: '`role="tooltip"` referenced by the trigger\'s `aria-describedby`. Never put essential info only in a tooltip.',
    do: 'Show shortcuts the way the platform writes them (Ctrl F / ⌘F).',
    dont: 'Don\'t use on text buttons that already say what they do.',
  },
  {
    name: 'Toast', group: 'Overlays', kind: 'component',
    summary: 'Small dark status message at the bottom-left, with Undo where possible.',
    anatomy: '32px min height · `surface-tooltip` fill, radius-md, `shadow-lg` · optional 12px spinner · message (text-sm) · optional underlined action.',
    variants: 'progress ("Message sending") · result with Undo ("Archived 3 threads").',
    states: 'enter (fade, `duration-slow`) · visible 4–6s · exit.',
    tokens: '`surface-tooltip`, `text-on-tooltip`, `shadow-lg`, `radius-md`, `text-sm`.',
    a11y: '`role="status"` (polite). Undo stays reachable by keyboard while visible; pause the timer on hover/focus.',
    do: 'Say what happened in past tense with a number.',
    dont: 'Don\'t stack more than one; replace the previous toast.',
  },
  {
    name: 'SettingsModal', group: 'Overlays', kind: 'component',
    summary: 'Large settings dialog: section navigation on the left, setting rows on the right.',
    anatomy: 'Scrim (`overlay`) · dialog (max 1050px, 32px inset from the viewport, radius-2xl, `shadow-xl`) · left nav 250px on `bg-sidebar` with section labels (Account, Workspace) and 28px items (external links end with an arrow) · content: title (text-base 600) over a hairline, then setting rows (title 14/500 + description 12 subtle, control on the right: inline Select, Toggle or secondary Button).',
    variants: 'Inbox (theme, thread style, auto-advance, font size) · AI · Gmail filters · Snippets · Signature (toggles + "Open") · Manage account.',
    states: 'open · section switch (content swaps, no animation) · closed.',
    tokens: '`overlay`, `bg`, `bg-sidebar`, `border`, `shadow-xl`, `radius-2xl`, `size-modal-max-width`, `size-modal-inset`, `size-settings-nav-width`.',
    a11y: '`role="dialog"` + `aria-modal`, labelled by the section title; focus trapped; Esc closes and restores focus to Settings.',
    do: 'Apply every change immediately.',
    dont: 'Don\'t add Save/Cancel buttons.',
  },
  {
    name: 'HoverPreview', group: 'Overlays', kind: 'component',
    summary: 'Read-only peek at a message body when hovering a row\'s subject.',
    anatomy: '320×≤220 card · `surface-raised`, radius-lg, `shadow-lg` · the message rendered at text-xs, clipped.',
    variants: 'plain text · HTML email (scaled down).',
    states: 'appears after a 600ms hover delay; disappears on leave.',
    tokens: '`surface-raised`, `shadow-lg`, `radius-lg`, `text-xs`.',
    a11y: 'Pointer-only enhancement; keyboard users open the thread instead. `aria-hidden` on the card.',
    do: 'Anchor under the pointer, inside the viewport.',
    dont: 'Don\'t make anything inside it interactive.',
  },
  // ---------------- Panels ----------------
  {
    name: 'ThreadView', group: 'Panels', kind: 'component',
    summary: 'An open thread in side peek, centre peek or full page.',
    anatomy: '44px bar (close peek », previous/next, "Auto label similar" secondary, then Remind, Mark unread, Label, Archive, Trash, More) · title (text-xl 700) · property row (label chips, status, "Add …" text buttons) · message header (sender 500, "To …" text-sm subtle, date right) · body (text-base, 1.6 leading, ≤62ch).',
    variants: 'side peek (right half, resizable, `border` on the left) · centre peek (modal) · full page — set in Settings › Thread style.',
    states: 'loading · loaded · property being edited (Menu/Input anchored under the chip).',
    tokens: '`bg`, `border`, `text`, `text-subtle`, `text-placeholder`, `text-xl`, `text-base`, `size-header-height`.',
    a11y: 'Peek is a `region` labelled by the subject; j/k move between threads; Esc closes and returns focus to the row.',
    do: 'Keep the list visible beside a side peek; highlight the open row with `surface-selected`.',
    dont: 'Don\'t repeat labels in the body area.',
  },
  {
    name: 'Composer', group: 'Panels', kind: 'component',
    summary: 'Floating compose window anchored bottom-right.',
    anatomy: '600px card, radius-2xl, `shadow-lg` · head (sender name + address in subtle, minimise, close) · recipients line (chips with ×, inline input, "Cc/Bcc" text button) · subject line · body (hairline above) · foot: split Send (primary; chevron schedules), "Draft saved" in `text-placeholder`, discard (trash) at the right.',
    variants: 'new message · reply (in-thread) · minimised (head only).',
    states: 'editing · draft saved · sending (Toast) · error.',
    tokens: '`surface-raised`, `shadow-lg`, `surface-hover`, `border`, `text`, `text-subtle`, `text-placeholder`, `accent`, `radius-2xl`, `size-composer-width`.',
    a11y: '`role="dialog"` (non-modal) labelled "New message"; Cmd/Ctrl+Enter sends; recipient chips have labelled remove buttons.',
    do: 'Autosave and say so quietly.',
    dont: 'Don\'t block the list behind it.',
  },
  {
    name: 'SidePanel', group: 'Panels', kind: 'component',
    summary: '400px right panel for configuring a view: Edit view, Properties, Add property.',
    anatomy: 'Head (optional back arrow, title text-md 600, close/collapse) · name row (30px icon tile + lg Input) · section labels (text-sm 500 subtle) · rows (icon, title + one-line description, chevron) · property rows (drag handle, icon, name, eye toggle, chevron) grouped "Shown in view" / "Hidden in view" · type rows (34px icon tile, name + description, + on hover) · footer action (Delete view, danger).',
    variants: 'Edit view · Properties · Add property · Edit property (see PropertyEditor) · Hover actions.',
    states: 'row hover (`surface-hover`) · dragging · focus-visible.',
    tokens: '`bg`, `border`, `surface-hover`, `shadow-sm`, `text`, `text-subtle`, `text-placeholder`, `danger-text`, `radius-md`, `size-panel-width`.',
    a11y: '`<aside>` labelled by its title; steps move focus to the new title; Esc closes. Drag handles have a keyboard alternative (move up/down).',
    do: 'Replace panel content for sub-steps and keep a back arrow.',
    dont: 'Don\'t stack panels.',
  },
  {
    name: 'PropertyEditor', group: 'Panels', kind: 'component',
    summary: 'Pick or edit the options of a select/status property.',
    anatomy: 'Menu: current value on top, "Select an option" label, options as Status/Tag pills (DEFAULT marker in 11px caps), "Edit property" item · Edit property panel: name Input, "Options" label with +, option rows with chevron, then Hide / Delete property actions.',
    variants: 'status (four fixed states) · select · multi-select.',
    states: 'option hover · default option · renaming.',
    tokens: 'Menu and SidePanel tokens + `tag-*`, `icon-*`, `text-2xs`.',
    a11y: 'Options are `role="option"`; the DEFAULT marker is text, not colour.',
    do: 'Mark the default option in words.',
    dont: 'Don\'t let two options share an ink in the same property.',
  },
  // ---------------- Onboarding ----------------
  {
    name: 'OptionList', group: 'Onboarding', kind: 'component',
    summary: 'Include/exclude choices during setup, each row a toggle button with a state chip.',
    anatomy: 'Question (text-md 600) + helper line · stack of 32px rows (radius-md, `shadow-sm` ring; included rows get an `accent-border` ring) with glyph, label and a chip ("Included" accent / "Excluded" gray) · full-width primary "Continue".',
    variants: 'include/exclude (default) · single choice.',
    states: 'included · excluded · hover · focus-visible.',
    tokens: '`bg`, `shadow-sm`, `accent-border`, `accent-subtle`, `accent-text`, `tag-gray-*`, `accent`.',
    a11y: 'Each row is a `button` with `aria-pressed`; the chip states the value in words.',
    do: 'Preview the result live next to the list.',
    dont: 'Don\'t use checkboxes and chips together; the row is the control.',
  },
  {
    name: 'TemplateCard', group: 'Onboarding', kind: 'component',
    summary: 'A view template in the gallery: tinted miniature, glyph, name and one-line purpose.',
    anatomy: '136px art (radius-lg, `tag-{ink}-bg` wash with a white mini-window showing sample chips) · glyph (16px, matching ink) · name (text-md 500) · description (text-xs subtle).',
    variants: 'Sales · Support · Calendar · Priority · Categories · Travel · Social · Newsletters… (one ink each).',
    states: 'default · hover (`shadow-md`) · focus-visible.',
    tokens: '`tag-*-bg`, `icon-*`, `bg`, `surface-selected`, `shadow-sm`, `shadow-md`, `radius-lg`.',
    a11y: 'Each card is one button whose name is the template name; the art is decorative.',
    do: 'Show real-looking chips in the miniature so the result is obvious.',
    dont: 'Don\'t use photos or third-party logos in the miniature.',
  },
  // ---------------- App ----------------
  {
    name: 'AppShell', group: 'App', kind: 'component',
    summary: 'The whole product frame: Sidebar, a view (ViewHeader + thread list) and an optional peek or panel.',
    anatomy: 'Grid: 240px Sidebar · list column · optional ThreadView (side peek) or SidePanel (400px). Below 1024px only the list shows.',
    variants: 'list · list + peek (`zl-app--peek`) · list + panel (`zl-app--panel`).',
    states: 'sidebar collapsed · peek open · panel open.',
    tokens: '`bg`, `bg-sidebar`, `border`, `size-sidebar-width`, `size-panel-width`, `size-header-height`.',
    a11y: 'Landmarks: `nav` (sidebar), `main` (view), `region`/`aside` (peek/panel). F6 cycles between them.',
    do: 'Use it as the marketing product visual (ScreenshotFrame) with fictional data.',
    dont: 'Don\'t use real people\'s names or screenshots of other products.',
  },
  {
    name: 'Card', group: 'Layout', kind: 'component',
    summary: 'Content block for marketing and settings summaries, lifted by a shadow ring rather than a border.',
    anatomy: '`bg`, radius-xl, `shadow-sm`, padding 24 · optional 32px icon tile on `bg-sidebar` with a coloured glyph · title (text-base 600) · body (text-md, text-muted).',
    variants: 'static · interactive (hover `shadow-md`).',
    states: 'default · hover (interactive) · focus-visible.',
    tokens: '`bg`, `bg-sidebar`, `shadow-sm`, `shadow-md`, `text`, `text-muted`, `radius-xl`.',
    a11y: 'An interactive card is a single link/button; don\'t nest buttons inside it.',
    do: 'One idea per card: glyph, title, one sentence.',
    dont: 'No coloured left borders or gradient fills.',
  },
  // ---------------- Marketing patterns ----------------
  {
    name: 'NavBar', group: 'Patterns', kind: 'pattern',
    summary: 'Sticky 56px site header: logo, four links, Log in and the primary CTA.',
    anatomy: 'Brand (24px mark + wordmark text) · links (30px, radius-md, text-muted; current in text 500) · ghost "Log in" · primary CTA · hairline below.',
    variants: 'desktop · mobile (links and Log in hidden; add a menu button).',
    states: 'link hover (`surface-hover`) · current (`aria-current`).',
    tokens: '`bg`, `border`, `text`, `text-muted`, `surface-hover`, `accent`, `z-sidebar`.',
    a11y: '`<header>` with a `<nav>`; skip link to main content.',
    do: 'Keep the CTA copy identical to the hero\'s.',
    dont: 'Don\'t add mega-menus.',
  },
  {
    name: 'Hero', group: 'Patterns', kind: 'pattern',
    summary: 'Centred headline, one sentence, two CTAs and the product itself.',
    anatomy: 'Headline (`display`, 700, ≤15ch) · lead (text-xl, text-muted) · primary xl + ghost xl buttons · note (text-sm, subtle) · AppShell visual cropped at the bottom (radius-2xl top corners, `shadow-xl`).',
    variants: 'desktop · mobile (headline drops to 4xl; buttons full width; visual 320px).',
    states: 'static.',
    tokens: '`text-display`, `text-xl`, `text`, `text-muted`, `text-subtle`, `accent`, `shadow-xl`, `radius-2xl`.',
    a11y: 'One `h1` per page; the visual is `role="img"` with a description.',
    do: 'Show the real UI (code-built, fictional data).',
    dont: 'No gradients, illustrations or stock photos.',
  },
  {
    name: 'FeatureGrid', group: 'Patterns', kind: 'pattern',
    summary: 'Section head plus a grid of Cards, on the `bg-sidebar` tint.',
    anatomy: 'Eyebrow (text-md 500, accent-text) · h2 (4xl 700) · lead · auto-fit grid of Cards (min 260px).',
    variants: '3 or 4 columns; tint or plain background.',
    states: 'static.',
    tokens: '`bg-sidebar`, `accent-text`, `text-4xl`, Card tokens.',
    a11y: 'Cards use `h3` under the section `h2`.',
    do: 'One glyph ink per card, varied.',
    dont: 'Don\'t exceed 6 cards.',
  },
  {
    name: 'ScreenshotFrame', group: 'Patterns', kind: 'pattern',
    summary: 'The AppShell inside simple window chrome, for marketing sections.',
    anatomy: '32px bar on `bg-sidebar` with three `surface-selected` dots · AppShell below · radius-2xl, `shadow-xl`.',
    variants: 'list · peek · panel (AppShell variants).',
    states: 'static.',
    tokens: '`bg`, `bg-sidebar`, `surface-selected`, `border`, `shadow-xl`, `radius-2xl`.',
    a11y: '`role="img"` + `aria-label` describing what is shown.',
    do: 'Use fictional names (Priya Raman, Northwind).',
    dont: 'Never use screenshots of third-party products.',
  },
  {
    name: 'Testimonial', group: 'Patterns', kind: 'pattern',
    summary: 'Quote cards, marked Placeholder until real, approved quotes exist.',
    anatomy: 'Card · quote (text-lg) · avatar initials (32px) · name (500) and role (subtle).',
    variants: 'two- or three-up.',
    states: 'static.',
    tokens: 'Card tokens + `text-lg`, `surface-selected`, `text-subtle`.',
    a11y: '`<figure>` + `<blockquote>` + `<figcaption>`.',
    do: 'Keep "Placeholder" visible until approved.',
    dont: 'Don\'t invent names or companies.',
  },
  {
    name: 'Pricing', group: 'Patterns', kind: 'pattern',
    summary: 'Three plan cards; the featured one has a 1.5px accent ring.',
    anatomy: 'Card per plan: name (+ Popular tag), price (3xl 700 + period), one-line description, feature list with accent checks, full-width button.',
    variants: 'monthly · yearly (toggle above, optional).',
    states: 'static.',
    tokens: 'Card tokens + `accent`, `tag-blue-*`, `text-3xl`, `border`.',
    a11y: 'Use a list for features; prices include the period in text.',
    do: 'Mark prices as placeholders until validated.',
    dont: 'Don\'t use strikethrough discounts.',
  },
  {
    name: 'FAQ', group: 'Patterns', kind: 'pattern',
    summary: 'Native details/summary list with hairline dividers.',
    anatomy: 'Summary (text-base 500) with a chevron · answer (text-md, text-muted, ≤62ch) · `border` rules.',
    variants: 'first open · all closed.',
    states: 'closed · open · focus-visible.',
    tokens: '`border`, `text`, `text-muted`, `text-subtle`, `duration-base`.',
    a11y: 'Native `<details>` keeps keyboard and screen-reader support.',
    do: 'Answer in one or two sentences.',
    dont: 'Don\'t hide pricing or privacy terms only here.',
  },
  {
    name: 'CTABand', group: 'Patterns', kind: 'pattern',
    summary: 'Closing call to action on the `bg-sidebar` tint with an email field.',
    anatomy: 'radius-2xl band · h2 (3xl 700) + lead · email Input (40px, white, `shadow-sm`) + primary xl button · note (text-sm subtle).',
    variants: 'with form · button only.',
    states: 'default · submitting · done (inline confirmation).',
    tokens: '`bg-sidebar`, `bg`, `shadow-sm`, `accent`, `text-3xl`, `radius-2xl`.',
    a11y: 'Visible or sr-only label on the email field; errors announced.',
    do: 'Repeat the hero\'s CTA wording.',
    dont: 'No dark or gradient band.',
  },
  {
    name: 'Footer', group: 'Patterns', kind: 'pattern',
    summary: 'Tinted footer: brand and tagline, three link columns, a base line.',
    anatomy: '`bg-sidebar` · brand + one-line tagline · columns with text-sm subtle headings and text-muted links · hairline base row.',
    variants: 'desktop 4 columns · mobile 2 columns.',
    states: 'link hover (text + underline).',
    tokens: '`bg-sidebar`, `border`, `text`, `text-muted`, `text-subtle`.',
    a11y: '`<footer>` with lists of links.',
    do: 'Keep legal links here.',
    dont: 'No social icon walls.',
  },
];
